### ISSUE TITLE
Any way to change the name of the notifcation?

### ISSUE THREAD

**Issue by thenitai** [flesch/hipchat-notify.js#2]
Hi there,

Posting to a room works perfectly. However, messages are coming from "Room Token". Is there a way to change this?

![screenshot_14_01_15_17_10](https://cloud.githubusercontent.com/assets/372121/5743276/39ca664e-9c10-11e4-944b-8a132d1fd15e.png)

**Comment by flesch** [comment]
HipChat's API v2 doesn't let you define a name through a parameter like v1 did, instead it uses the Label field when you create the token.

![label](https://cloud.githubusercontent.com/assets/13259/5743650/4ed1d246-9be0-11e4-9bd5-ce48b4b6bf09.png)

**Comment by thenitai** [comment]
My bad. Thank you for pointing me in the right direction.

On Wed, Jan 14, 2015 at 5:29 PM, John Flesch <notifications@github.com>
wrote:

> Closed #2 <https://github.com/flesch/hipchat-notify.js/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flesch/hipchat-notify.js/issues/2#event-218890492>.
>



-- 
See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com
