### ISSUE TITLE
From field does not remove my name

### ISSUE THREAD

**Issue by chetanbasuray** [flesch/hipchat-notify.js#5]
I post a notification to hipchat using the following code:

`hipchat.error({ message:'Tests are failing on '+enviroment+ ' due to the following error: '+JSON.stringify(error), notify:false, from:'SmokeTests-'+enviroment });`

The problem I am facing is that the from field just appends SmokeTests-${environment} to my username in Hipchat but does not replace it completely. Is it possible to add this as a functionality or solve this issue some other way?

**Comment by flesch** [comment]
@chetanbasuray Something may have changed with HipChat since I've last looked at this module.

[HipChat is shutting down](https://www.atlassian.com/partnerships/slack) anyway, so I don't think it mays sense to work on a fix.
